spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

logging:
  level:
    com.portfolio.management: WARN
    root: WARN
  file:
    name: /var/log/portfolio-management/application.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  compression:
    enabled: true